# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/regions
Accept: application/json

###

GET http://127.0.0.1:8000/questions?region=Wielkopolska&powiat=poznański
Accept: application/json

###

GET http://127.0.0.1:8000/questions
Accept: application/json

###
